stages:
   - build
   - deploy

build_app:
   image: node:16
   stage: build
   only:
      - develop
   script:
      - echo "proses build"
      - npm install
      - echo "Install sukses"
      - npm run build
      - echo "Build sukses"
   cache:
     paths:
       - node_modules/ 
   artifacts:
      paths:
         - dist/
      expire_in: 1 hour

deploy_staging:
   image : alpine:latest
   stage: deploy
   only:
      - develop
   before_script:
      - echo "Install SSH"
      - apk add --no-cache openssh
      - echo "Create Key"
      - mkdir -p ~/.ssh
      - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
           
   script:
      - scp -r dist/* $TARGET
